### ISSUE TITLE
Segfault when using the download command

### ISSUE THREAD

**Issue by JPFrancoia** [8cylinder/tv-overlord#13] opened 2016-06-11 09:54 UTC
Hi,

Your tool looks promising. However, I have a little problem:

```bash
tvol download Suits
>> torrent
Searching for: Suits...[1]    4459 segmentation fault (core dumped)  tvol download Suits
```

I'm on Manjaro Linux. Did you already encounter this problem ?

**Comment by 8cylinder** [comment] 2016-06-11 16:18
The only time I see a segfault is when I run tvol over an ssh connection with X forwarding.  Transmission crashes with a segfault when it gets passed the magnet link.  But by the looks of the output you showed me, the segfault is happening before you get the list to choose the download.

I'm going to try tvol in a vm running Manjaro to try and cause the error.  Which version of Manjaro are you using, 16.06?

b.t.w, I've uploaded a newer version that gets rid of debug string `>> torrent` that I accidentally left in.  There are a few other changes but they probably won't fix your issue.

**Comment by JPFrancoia** [comment] 2016-06-11 17:24
Hi,

I tried the master branch after your last update (before, I was using the version directly available from pip). I don't get the segfault anymore, but I think other things are broken now:

```bash
tvol download 'Suits'                                                                                                                                                               130 ↵
{'name': 'Suits', 'status': 'active', 'thetvdb_series_id': '247808', 'episode': 0, 'ragetv_series_id': None, 'search_engine_name': None, 'season': 0}
```
Or:

```bash
tvol calendar
                     Jun                 Jul                            Aug                            Sep                           Oct                            Nov                       
                     ::.....::.....::....|::.....::.....::.....::.....::|....::.....::.....::.....::...|.::.....::.....::.....::.....|:.....::.....::.....::.....::.|...::.....::.....::.....:
{'episode': 0, 'season': 0, 'ragetv_series_id': None, 'search_engine_name': None, 'status': 'active', 'thetvdb_series_id': '80379', 'name': 'The Big Bang Theory'}
```

I'll be happy to continue testing ! I also opened a pull request, there is a small error in the setup.py that blocks installation from pip.

**Comment by 8cylinder** [comment] 2016-06-11 18:09
I am sorry, a few minutes ago I realized I uploaded a version with some more debug code, and I've uploaded a version with that fixed.  That is version 0.9.20.

<sigh>

Thanks, this really needs some testing other than me!

**Comment by 8cylinder** [comment] 2016-06-11 19:25
I setup Manjaro 16.06 32 bit with XFCE in a vm and everything ran correctly.  I'm not familiar with Manjaro so let me know if I should do something different.  The steps I took once the live cd was running:

1. `pacman -S python-pip`
1. `pacman -S transmission-gtk` (I also tried with `pacman -S deluge`)
1. `pip install tvoverlord`
1. `tvol`
1. `tvol addnew suits`
1. `tvol showmissing`
1. `tvol download`

And everything worked properly.

Anything you can tell me about your setup would be helpful.

Thanks for your help!

**Comment by JPFrancoia** [comment] 2016-06-11 20:11
Ok I pulled your last changes on master, but I got the segfault back:

```bash
tvol download
Searching for: Suits...[1]    16791 segmentation fault (core dumped)  tvol download
```
I am on Manjaro 16.06 64 bits, and my kernel is 4.4.12-1 (but I don't think it should matter here).
I use zsh, but I also tried to run the commands from bash. I didn't put anything in my bashrc or zshrc.

What can I try ? Dos tvoverlord works on 64 bits system ?

**Comment by 8cylinder** [comment] 2016-06-12 16:34
> Does tvoverlord works on 64 bits system ?

Yes, It works anywhere that Python works

> What happens if a torrent provider is down ?

It's not a problem, it will just timeout.  Thats a part of the design of tvol, since torrent search engines come and go a lot.

---

As far as the current issue goes, It seems that a segfault in python is caused by running out of memory
or a bug in a C module.

If it's a matter of resource limits, you can check with `ulimit -s`.  This will give you your current limit.  Try `ulimit -s <new value>` to adjust it for your current session.  Keep doubling the value until it works (or not).

I got this from http://stackoverflow.com/a/11368425

**Comment by JPFrancoia** [comment] 2016-06-12 16:54
It's probably a bug in a C module. I'm sorry to  disappoint you with `ulimit -s`: it returns `unlimited`.

So basically, one of my modules causes the crash. Here is a list of the modules I installed with pip. Could you check you use the same versions of the modules we have in common ?

[out.txt](https://github.com/8cylinder/tv-overlord/files/310858/out.txt)

**Comment by 8cylinder** [comment] 2016-06-12 18:10
Add this to the first line of tvol.py (just below the `#!/usr/bin/env python3` comment:

```python
import faulthandler
faulthandler.enable()
```
And then run `tvol`

This turns on error reporting for segfaults.  It won't say where in the C mod the error is, but it will say where the mod was called in Python.  This should tell us the module responsible.

I compared your list with mine and the only mods the same are the dependencies for tvol, so unfortunately, that's not very helpful.

I see you have virtualenv installed; try installing tvol there, it might work.  A clean environment might help.

**Comment by JPFrancoia** [comment] 2016-06-13 07:42
Ok, first of all, running tvol in a virtualenv works. So there is a problem with  my installation of Python.

I added the 2 lines you mentioned and here is the result:

```
Searching for: Suits...Fatal Python error: Segmentation fault

Thread 0x00002b6e8ad66700 (most recent call first):
  File "/usr/lib/python3.5/socket.py", line 732 in getaddrinfo
  File "/usr/lib/python3.5/site-packages/urllib3/util/connection.py", line 67 in create_connection
  File "/usr/lib/python3.5/site-packages/urllib3/connection.py", line 142 in _new_conn
  File "/usr/lib/python3.5/site-packages/urllib3/connection.py", line 167 in connect
  File "/usr/lib/python3.5/http/client.py", line 854 in send
  File "/usr/lib/python3.5/http/client.py", line 911 in _send_output
  File "/usr/lib/python3.5/http/client.py", line 1079 in endheaders
  File "/usr/lib/python3.5/http/client.py", line 1128 in _send_request
  File "/usr/lib/python3.5/http/client.py", line 1083 in request
  File "/usr/lib/python3.5/site-packages/urllib3/connectionpool.py", line 362 in _make_request
  File "/usr/lib/python3.5/site-packages/urllib3/connectionpool.py", line 578 in urlopen
  File "/usr/lib/python3.5/site-packages/requests/adapters.py", line 403 in send
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 585 in send
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 475 in request
  File "/usr/lib/python3.5/site-packages/requests/api.py", line 57 in request
  File "/usr/lib/python3.5/site-packages/requests/api.py", line 71 in get
  File "/usr/lib/python3.5/site-packages/tvoverlord/search_providers/onethreethreesevenx_to.py", line 76 in _get_details
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55 in run
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 66 in _worker
  File "/usr/lib/python3.5/threading.py", line 862 in run
  File "/usr/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/usr/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00002b6e8ab65700 (most recent call first):
  File "/usr/lib/python3.5/socket.py", line 732 in getaddrinfo
  File "/usr/lib/python3.5/site-packages/urllib3/util/connection.py", line 67 in create_connection
  File "/usr/lib/python3.5/site-packages/urllib3/connection.py", line 142 in _new_conn
  File "/usr/lib/python3.5/site-packages/urllib3/connection.py", line 167 in connect
  File "/usr/lib/python3.5/http/client.py", line 854 in send
  File "/usr/lib/python3.5/http/client.py", line 911 in _send_output
  File "/usr/lib/python3.5/http/client.py", line 1079 in endheaders
  File "/usr/lib/python3.5/http/client.py", line 1128 in _send_request
  File "/usr/lib/python3.5/http/client.py", line 1083 in request
  File "/usr/lib/python3.5/site-packages/urllib3/connectionpool.py", line 362 in _make_request
  File "/usr/lib/python3.5/site-packages/urllib3/connectionpool.py", line 578 in urlopen
  File "/usr/lib/python3.5/site-packages/requests/adapters.py", line 403 in send
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 585 in send
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 475 in request
  File "/usr/lib/python3.5/site-packages/requests/api.py", line 57 in request
  File "/usr/lib/python3.5/site-packages/requests/api.py", line 71 in get
  File "/usr/lib/python3.5/site-packages/tvoverlord/search_providers/onethreethreesevenx_to.py", line 76 in _get_details
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55 in run
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 66 in _worker
  File "/usr/lib/python3.5/threading.py", line 862 in run
  File "/usr/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/usr/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00002b6e8a964700 (most recent call first):
  File "/usr/lib/python3.5/ssl.py", line 570 in read
  File "/usr/lib/python3.5/ssl.py", line 786 in read
  File "/usr/lib/python3.5/ssl.py", line 924 in recv_into
  File "/usr/lib/python3.5/socket.py", line 575 in readinto
  File "/usr/lib/python3.5/http/client.py", line 243 in _read_status
  File "/usr/lib/python3.5/http/client.py", line 282 in begin
  File "/usr/lib/python3.5/http/client.py", line 1174 in getresponse
  File "/usr/lib/python3.5/site-packages/urllib3/connectionpool.py", line 387 in _make_request
  File "/usr/lib/python3.5/site-packages/urllib3/connectionpool.py", line 578 in urlopen
  File "/usr/lib/python3.5/site-packages/requests/adapters.py", line 403 in send
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 585 in send
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 475 in request
  File "/usr/lib/python3.5/site-packages/requests/api.py", line 57 in request
  File "/usr/lib/python3.5/site-packages/requests/api.py", line 71 in get
  File "/usr/lib/python3.5/site-packages/tvoverlord/search_providers/eztv_ag.py", line 31 in search
  File "/usr/lib/python3.5/site-packages/tvoverlord/search.py", line 45 in job
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55 in run
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 66 in _worker
  File "/usr/lib/python3.5/threading.py", line 862 in run
  File "/usr/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/usr/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00002b6e8a763700 (most recent call first):
  File "/usr/lib/python3.5/ssl.py", line 628 in do_handshake
  File "/usr/lib/python3.5/ssl.py", line 983 in do_handshake
  File "/usr/lib/python3.5/ssl.py", line 747 in __init__
  File "/usr/lib/python3.5/ssl.py", line 376 in wrap_socket
  File "/usr/lib/python3.5/site-packages/urllib3/util/ssl_.py", line 308 in ssl_wrap_socket
  File "/usr/lib/python3.5/site-packages/urllib3/connection.py", line 289 in connect
  File "/usr/lib/python3.5/site-packages/urllib3/connectionpool.py", line 814 in _validate_conn
  File "/usr/lib/python3.5/site-packages/urllib3/connectionpool.py", line 351 in _make_request
  File "/usr/lib/python3.5/site-packages/urllib3/connectionpool.py", line 578 in urlopen
  File "/usr/lib/python3.5/site-packages/requests/adapters.py", line 403 in send
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 585 in send
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 475 in request
  File "/usr/lib/python3.5/site-packages/requests/api.py", line 57 in request
  File "/usr/lib/python3.5/site-packages/requests/api.py", line 71 in get
  File "/usr/lib/python3.5/site-packages/tvoverlord/search_providers/rarbg_to.py", line 49 in search
  File "/usr/lib/python3.5/site-packages/tvoverlord/search.py", line 45 in job
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55 in run
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 66 in _worker
  File "/usr/lib/python3.5/threading.py", line 862 in run
  File "/usr/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/usr/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00002b6e8a562700 (most recent call first):
  File "/usr/lib/python3.5/threading.py", line 293 in wait
  File "/usr/lib/python3.5/threading.py", line 549 in wait
  File "/usr/lib/python3.5/threading.py", line 849 in start
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 129 in _adjust_thread_count
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 113 in submit
  File "/usr/lib/python3.5/site-packages/tvoverlord/search_providers/onethreethreesevenx_to.py", line 59 in <dictcomp>
  File "/usr/lib/python3.5/site-packages/tvoverlord/search_providers/onethreethreesevenx_to.py", line 59 in search
  File "/usr/lib/python3.5/site-packages/tvoverlord/search.py", line 45 in job
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55 in run
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 66 in _worker
  File "/usr/lib/python3.5/threading.py", line 862 in run
  File "/usr/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/usr/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00002b6e8a361700 (most recent call first):
  File "/usr/lib/python3.5/ssl.py", line 628 in do_handshake
  File "/usr/lib/python3.5/ssl.py", line 983 in do_handshake
  File "/usr/lib/python3.5/ssl.py", line 747 in __init__
  File "/usr/lib/python3.5/ssl.py", line 376 in wrap_socket
  File "/usr/lib/python3.5/http/client.py", line 1237 in connect
  File "/usr/lib/python3.5/http/client.py", line 854 in send
  File "/usr/lib/python3.5/http/client.py", line 911 in _send_output
  File "/usr/lib/python3.5/http/client.py", line 1079 in endheaders
  File "/usr/lib/python3.5/http/client.py", line 1128 in _send_request
  File "/usr/lib/python3.5/http/client.py", line 1083 in request
  File "/usr/lib/python3.5/urllib/request.py", line 1240 in do_open
  File "/usr/lib/python3.5/urllib/request.py", line 1283 in https_open
  File "/usr/lib/python3.5/urllib/request.py", line 443 in _call_chain
  File "/usr/lib/python3.5/urllib/request.py", line 483 in _open
  File "/usr/lib/python3.5/urllib/request.py", line 465 in open
  File "/usr/lib/python3.5/urllib/request.py", line 686 in http_error_302
  File "/usr/lib/python3.5/site-packages/feedparser.py", line 2766 in http_error_301
  File "/usr/lib/python3.5/urllib/request.py", line 443 in _call_chain
  File "/usr/lib/python3.5/urllib/request.py", line 503 in error
  File "/usr/lib/python3.5/urllib/request.py", line 581 in http_response
  File "/usr/lib/python3.5/urllib/request.py", line 471 in open
  File "/usr/lib/python3.5/site-packages/feedparser.py", line 2866 in _open_resource
  File "/usr/lib/python3.5/site-packages/feedparser.py", line 3841 in parse
  File "/usr/lib/python3.5/site-packages/tvoverlord/search_providers/kickass_to.py", line 48 in search
  File "/usr/lib/python3.5/site-packages/tvoverlord/search.py", line 45 in job
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55 in run
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 66 in _worker
  File "/usr/lib/python3.5/threading.py", line 862 in run
  File "/usr/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/usr/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00002b6e8a160700 (most recent call first):
  File "/usr/lib/python3.5/ssl.py", line 570 in read
  File "/usr/lib/python3.5/ssl.py", line 786 in read
  File "/usr/lib/python3.5/ssl.py", line 924 in recv_into
  File "/usr/lib/python3.5/socket.py", line 575 in readinto
  File "/usr/lib/python3.5/http/client.py", line 243 in _read_status
  File "/usr/lib/python3.5/http/client.py", line 282 in begin
  File "/usr/lib/python3.5/http/client.py", line 1174 in getresponse
  File "/usr/lib/python3.5/site-packages/urllib3/connectionpool.py", line 387 in _make_request
  File "/usr/lib/python3.5/site-packages/urllib3/connectionpool.py", line 578 in urlopen
  File "/usr/lib/python3.5/site-packages/requests/adapters.py", line 403 in send
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 585 in send
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 179 in resolve_redirects
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 606 in <listcomp>
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 606 in send
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 475 in request
  File "/usr/lib/python3.5/site-packages/requests/api.py", line 57 in request
  File "/usr/lib/python3.5/site-packages/requests/api.py", line 71 in get
  File "/usr/lib/python3.5/site-packages/tvoverlord/search_providers/thepiratebay_sx.py", line 56 in search
  File "/usr/lib/python3.5/site-packages/tvoverlord/search.py", line 45 in job
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55 in run
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 66 in _worker
  File "/usr/lib/python3.5/threading.py", line 862 in run
  File "/usr/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/usr/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00002b6e89930700 (most recent call first):
  File "/usr/lib/python3.5/threading.py", line 293 in wait
  File "/usr/lib/python3.5/queue.py", line 164 in get
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 64 in _worker
  File "/usr/lib/python3.5/threading.py", line 862 in run
  File "/usr/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/usr/lib/python3.5/threading.py", line 882 in _bootstrap

Current thread 0x00002b6e8972f700 (most recent call first):
  File "/usr/lib/python3.5/site-packages/libxml2.py", line 6829 in Read
  File "/usr/lib/python3.5/site-packages/drv_libxml2.py", line 170 in parse
  File "/usr/lib/python3.5/site-packages/feedparser.py", line 3957 in parse
  File "/usr/lib/python3.5/site-packages/tvoverlord/search_providers/bitsnoop.py", line 46 in search
  File "/usr/lib/python3.5/site-packages/tvoverlord/search.py", line 45 in job
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55 in run
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 66 in _worker
  File "/usr/lib/python3.5/threading.py", line 862 in run
  File "/usr/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/usr/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00002b6e80567980 (most recent call first):
  File "/usr/lib/python3.5/threading.py", line 293 in wait
  File "/usr/lib/python3.5/threading.py", line 549 in wait
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 215 in as_completed
  File "/usr/lib/python3.5/site-packages/tvoverlord/search.py", line 113 in search
  File "/usr/lib/python3.5/site-packages/tvoverlord/series.py", line 156 in download_missing
  File "/usr/lib/python3.5/site-packages/tvoverlord/tvol.py", line 479 in download
  File "/usr/lib/python3.5/site-packages/click/core.py", line 513 in invoke
  File "/usr/lib/python3.5/site-packages/click/core.py", line 868 in invoke
  File "/usr/lib/python3.5/site-packages/click/core.py", line 1039 in invoke
  File "/usr/lib/python3.5/site-packages/click/core.py", line 675 in main
  File "/usr/lib/python3.5/site-packages/click/core.py", line 695 in __call__
  File "/usr/bin/tvol", line 9 in <module>
[1]    31581 segmentation fault (core dumped)  tvol download
```

I have never used faulthandler before, but if I understand well, the click module is the problem here, isn't it ? But I installed the same click in my virtualenv and tvol works.

**Comment by 8cylinder** [comment] 2016-06-13 17:08
I think I know whats going on, but unfortunatly it won't be much use for you.  Although, I have a work arround that might be good enough.

Since this works in a virtualenv, that means there is a version mismatch somewhere.  But, when I compare version of what I have and you have for tvol's direct dependencies, they are the same.

Looking at the output from faulthandler, it looks like the error is coming from feedparser.  The output from faulthandler happens when tvol has started a bunch of threads to search all the websites simultaneously.  Each of those threads are search engines, except for the bottom one which is the parent thread.  The one marked 'Current thread' is (I think) the one where the error is happening.  Line 46 in bitsnoop.py is where I use feedparser to parse the search results.  Then feedparser calls libxml2 and that's where it stops with a segfault.

So, since it works in a virtualenv it looks like there is an issue around libxml2 versions.

My recomendation is to remove the globaly installed tvol and keep the one in virtualenv and maybe write a simple wrapper script that activates the virtualenv when you call `tvol`.

```bash
virtloc='<location of virtualenv>'
cd $virtloc
source ./venv/bin/activate
tvol $*
deactivate
```

Also, if you want to use the post download scrips, their location is .../venv/bin/transmission_done or .../venv/bin/deluge_done.  With those you shouldn't need to use them in the virtualenv since they don't use feedparser.

**Comment by JPFrancoia** [comment] 2016-06-14 09:19
Ok, based on what you said, I'm starting to suspect something. You're probably right about the mismatch version.

I think some of the libraries installed by my system are "newer" than the ones available with pip. Example:

```
pip search lxml
...
lxml (3.5.0)                   - Powerful and Pythonic XML processing library combining libxml2/libxslt with the ElementTree API.
  INSTALLED: 3.6.0
  LATEST:    3.5.0
```

That's because I have the package python-lxml installed (installation through Pacman on Manjaro). So the problem is not with the direct dependencies of tvol, but more with the "other" dependencies.

Could you check the versions of the python packages we have in common please ?

**Comment by 8cylinder** [comment] 2016-06-14 13:50
Global installed list:
[pip3-packages.txt](https://github.com/8cylinder/tv-overlord/files/313968/pip3-packages.txt)

Installed in a virtualenv by tvol:
```
appdirs (1.4.0)
beautifulsoup4 (4.4.1)
click (6.6)
docopt (0.6.2)
feedparser (5.2.1)
pip (8.1.2)
pkg-resources (0.0.0)
psutil (4.2.0)
python-dateutil (2.5.3)
requests (2.10.0)
requests-cache (0.4.12)
setuptools (22.0.5)
six (1.10.0)
tvdb-api (1.10)
tvoverlord (0.9.15, /home/sm/projects/media-downloader/tvoverlord)
wheel (0.29.0)
```

As you can see, lxml is at version 3.5.  3.6 is the current dev version. It looks like pacman is installing dev versions for some packages.

Note that tvol doesn't use lxml; it used to but I switched beautifulsoup4 to use the built-in parser (html.parser) instead.  Also, I don't think any dependency uses it either otherwise it would show in the virtualenv pip list.

**Comment by 8cylinder** [comment] 2016-08-13 03:24
I'm going to mark this as closed, if there is still a problem re-open it.

**Closed by 8cylinder** 2016-08-13 03:24 UTC
