### ISSUE TITLE
'cache_location' error when trying to retrieve data 

### ISSUE THREAD

**Issue by GithubRandomUser** [8cylinder/tv-overlord#68] opened 2017-05-25 13:10 UTC
Getting the following error for the last week.

Error #: 101
Error message from stack trace:
'cache_location'

Appreciate any help

**Comment by janschulz** [comment] 2017-05-25 23:14
If you use `--no-cache` it ends up with a new error:

```
[...]
Error #: 102

Error message from stack trace:

There was an error with the XML retrieved from thetvdb.com:
no element found: line 1071, column 54
If this does not resolve the issue, please try again later. If the error persists, report a bug on
http://dbr.lighthouseapp.com/projects/13342-tvdb_api/overview
```

Looking for that, I ended up with https://dbr.lighthouseapp.com/projects/13342/tickets/107-xml-cutoff-and-thus-malformed-for-fargo-allenxml-endpoint#ticket-107-1 and https://forums.thetvdb.com/viewtopic.php?f=17&t=37586&sid=92f3f3f04ac582264def567e6ecd3681&start=10

As far as I understnd the issue, APIv1 is deprecated and broken and v2 should be used?

**Comment by janschulz** [comment] 2017-05-28 13:45
If you install tvdb_api from https://github.com/janschulz/tvdb_api/tree/v1_compat it works again (not sure how far, but for my usecase it was enough)

**Comment by kbaikov** [comment] 2017-05-30 18:59
I can confirm, that after `pip install -U git+https://github.com/janschulz/tvdb_api.git@v1_compat` everything works.
Thank you @janschulz !

**Comment by janschulz** [comment] 2017-05-30 19:50
The changes are now submitted upstream: https://github.com/dbr/tvdb_api/pull/58

**Comment by GithubRandomUser** [comment] 2017-05-30 22:18
@kbaikov I was able to install tvdb_api but i am still getting the error when i try to do tvol download. Do i need to update any of the configurations in tvol to tell it to use the tvdb_api?

**Comment by kbaikov** [comment] 2017-05-31 05:35
@GithubRandomUser I did not need to update anything else.
Make sure you install v1_compat branch.

**Comment by 8cylinder** [comment] 2017-09-27 21:57
I've updated tvol to use tvdb_api v2.0.  This _should_ solve the issues with the bad xml coming from thetvdb.com.  So far I've only used it on linux but it looks like its working properly. 

I'm going to close this ticket, but open it again (or start a new one) if there is still a problem.

**Closed by 8cylinder** 2017-09-27 21:57 UTC
